### ISSUE TITLE
如何生成ttf文件？

### ISSUE THREAD

**Issue by mayidu** [hmgle/gendotmatrix#2]
您好，我看您最终生成的是.font的文件，请问一下，如何生成.ttf的文件，能够在windows下使用，谢谢！

**Comment by hmgle** [comment]
您好。
这个工具不能够生成 TrueTypeFont(ttf) 字体文件，它只能把字体文件转换为点阵字体文件，安装了依赖库之后所有平台都能使用。

**Comment by mayidu** [comment]
感谢您的回复，您能给我详细说一下吗，需要什么依赖库呢，我是需要在Windows下使用，具体的到时候是如何使用呢，感谢您！

**Comment by hmgle** [comment]
> 感谢您的回复，您能给我详细说一下吗，需要什么依赖库呢，我是需要在Windows下使用，具体的到时候是如何使用呢，感谢您！

https://github.com/hmgle/gendotmatrix#install `pip install gendotmatrix` 直接安装就可以了呀。

**Comment by mayidu** [comment]
你是说安装了gendotmatrix后，生成的字体就可以使用了吗？那要怎么使用呢，这个不是用来生成.font文件的吗，不是很理解，还请您能说的再详细一点呢，感谢！

**Comment by hmgle** [comment]
> 你是说安装了gendotmatrix后，生成的字体就可以使用了吗？那要怎么使用呢，这个不是用来生成.font文件的吗，不是很理解，还请您能说的再详细一点呢，感谢！

`gendotmatrix.py --help`
如果您没有明确使用场景，请不要使用。

**Comment by mayidu** [comment]
感谢回复，能否请教下，您的这个使用场景具体是什么呢？我的理解是将比如宋体的字体转换为宋体点阵字体，然后就可以直接使用宋体点阵字体了，是这样吗，还是我的理解不到位呢？感谢！

**Comment by hmgle** [comment]
> 感谢回复，能否请教下，您的这个使用场景具体是什么呢？我的理解是将比如宋体的字体转换为宋体点阵字体，然后就可以直接使用宋体点阵字体了，是这样吗，还是我的理解不到位呢？感谢！

是的。

**Comment by shenchenfei** [comment]
> 
> 
> 感谢回复，能否请教下，您的这个使用场景具体是什么呢？我的理解是将比如宋体的字体转换为宋体点阵字体，然后就可以直接使用宋体点阵字体了，是这样吗，还是我的理解不到位呢？感谢！

你好，请问你搞清楚生成的.font文件如何使用了吗？
